server:
  applicationConnectors:
    - type: http
      port: 9001

httpClient:
  timeout: 500ms
  connectionTimeout: 500ms
  timeToLive: 1h
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0ms
  retries: 0
  userAgent: addressResolver

hereCom:
  type: https
  domainName: discover.search.hereapi.com
  geoCodePath: /v1/geocode
  apiKey: ${API_KEY}